### ISSUE TITLE
Outdated version on Decky Loader

### ISSUE THREAD

**Issue by vazome** [jwhitlow45/free-loader#2]
In store section of Decky Loader the plugin version is 1.1.0-1 while the latest release in this repository is [1.2.0](https://github.com/jwhitlow45/free-loader/releases/tag/1.2.0)

**Comment by jwhitlow45** [comment]
This is because the repo is updated but has not been merged into the Decky loader store due to testing not being completed. Updates are a bit slow because testing takes a while unfortunately. You're welcome to build and deploy it to your Deck manually from this repo if you'd like the features sooner but it may be buggy.
